# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df35bcfcbc334fde9a005d6842a50f1d4b53c6224cc0810f50edb88f46669d305359f4f4333d29b229417bb5a8e6233ba0e952b5d13613f3f0288f11d5300954

test:
  secret_key_base: 172ac7ef1fed6dc3fd2bf9f4be413a73b80ef6298167d58744d7d664825590a07a5987feecebd3398b0d6f9ceb1dba4094d1684579c55bc74ffbc7dde95d7bc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
